!function(a,d){function g(b,m){var a=b.createElement("p"),d=b.getElementsByTagName("head")[0]||b.documentElement;return a.innerHTML="x<style>"+m+"</style>",d.insertBefore(a.lastChild,d.firstChild)}function k(){var b=e.elements;return"string"==typeof b?b.split(" "):b}function c(b){var m=x[b[y]];return m||(m={},r++,b[y]=r,x[r]=m),m}function f(b,m,a){if(m||(m=d),h)return m.createElement(b);a||(a=c(m));var q;return q=a.a[b]?a.a[b].cloneNode():C.test(b)?(a.a[b]=a.b(b)).cloneNode():a.b(b),!q.canHaveChildren||
D.test(b)||q.q?q:a.c.appendChild(q)}function p(b,a){a.a||(a.a={},a.b=b.createElement,a.h=b.createDocumentFragment,a.c=a.h());b.createElement=function(d){return e.f?f(d,b,a):a.b(d)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+k().join().replace(/[\w\-:]+/g,function(b){return a.b(b),a.c.createElement(b),'c("'+b+'")'})+");return n}")(e,a.c)}function z(b){b||(b=d);var a=c(b);return!e.e||v||a.i||(a.i=!!g(b,"article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}")),
h||p(b,a),b}function E(b){for(var a,d=b.attributes,c=d.length,g=b.ownerDocument.createElement(u+":"+b.nodeName);c--;)a=d[c],a.specified&&g.setAttribute(a.nodeName,a.nodeValue);return g.style.cssText=b.style.cssText,g}function A(a){function d(){clearTimeout(e.d);t&&t.removeNode(!0);t=null}var t,q,e=c(a),f=a.namespaces,h=a.parentWindow;return!F||a.k?a:("undefined"==typeof f[u]&&f.add(u),h.attachEvent("onbeforeprint",function(){d();var c,n,e;e=a.styleSheets;for(var f=[],l=e.length,h=Array(l);l--;)h[l]=
e[l];for(;e=h.pop();)if(!e.disabled&&G.test(e.media)){try{c=e.imports,n=c.length}catch(p){n=0}for(l=0;n>l;l++)h.push(c[l]);try{f.push(e.cssText)}catch(r){}}c=f.reverse().join("").split("{");n=c.length;l=RegExp("(^|[\\s,>+~])("+k().join("|")+")(?=[[\\s,>+~#.:]|$)","gi");for(h="$1"+u+"\\:$2";n--;)f=c[n]=c[n].split("}"),f[f.length-1]=f[f.length-1].replace(l,h),c[n]=f.join("}");f=c.join("{");n=a.getElementsByTagName("*");l=n.length;h=RegExp("^(?:"+k().join("|")+")$","i");for(e=[];l--;)c=n[l],h.test(c.nodeName)&&
e.push(c.g(E(c)));q=e;t=g(a,f)}),h.attachEvent("onafterprint",function(){for(var a=q,b=a.length;b--;)a[b].removeNode();clearTimeout(e.d);e.d=setTimeout(d,500)}),a.k=!0,a)}var v,h,w=a.j||{},D=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,C=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,y="_html5shiv",r=0,x={};!function(){try{var a=d.createElement("a");a.innerHTML="<xyz></xyz>";v="hidden"in a;var c;if(!(c=1==a.childNodes.length)){d.createElement("a");
var e=d.createDocumentFragment();c="undefined"==typeof e.cloneNode||"undefined"==typeof e.createDocumentFragment||"undefined"==typeof e.createElement}h=c}catch(f){h=v=!0}}();var e={elements:w.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output picture progress section summary template time video",version:"3.7.0",e:!1!==w.e,p:h,f:!1!==w.f,type:"default",n:z,createElement:f,createDocumentFragment:function(a,e){if(a||
(a=d),h)return a.createDocumentFragment();e=e||c(a);for(var f=e.c.cloneNode(),g=0,p=k(),r=p.length;r>g;g++)f.createElement(p[g]);return f}};a.j=e;z(d);var G=/^$|\b(?:all|print)\b/,u="html5shiv",F=!h&&function(){var b=d.documentElement;return!("undefined"==typeof d.namespaces||"undefined"==typeof d.parentWindow||"undefined"==typeof b.g||"undefined"==typeof b.removeNode||"undefined"==typeof a.attachEvent)}();e.type+=" print";e.o=A;A(d)}(this,document);
String.prototype.contains=function(a){return-1!==this.indexOf(a)};Array.prototype.contains=function(a){return-1!==this.indexOf(a)};
function B(){var a,d=location.hash,d=d.substring(3,d.length),g=document.querySelectorAll("article");a=[];for(var k=0;k<g.length;k++){var c=g[k].id;c.contains("!/")&&a.push(c.substring(2,c.length))}a.contains(d)?(c=d,d=document.head.querySelector('link[rel="prev"]'),g=document.head.querySelector('link[rel="next"]'),k=a[0>a.indexOf(c)-1?a.length-1:a.indexOf(c)-1],a=a[a.indexOf(c)+1>a.length?0:a.indexOf(c)+1],a=void 0===a?"home":a,k=void 0===k?"home":k,d=null===d?document.createElement("link"):d,g=null===
g?document.createElement("link"):g,d.rel="prev",g.rel="next",d.href="#!/"+k,g.href="#!/"+a,document.head.appendChild(d),document.head.appendChild(g),a=!0):a=!1;a||(location.hash="!/home")}window.onload=function(){B();(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&document.body.classList.add("ie")};window.onhashchange=B;